name: Daily README Updater

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  waka:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        id: first-attempt
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          SHOW_TITLE: false
          COMMIT_MESSAGE: ⚡ Updated Weekly Coding Stats
        continue-on-error: true
      - name: Wait 30 minutes
        run: sleep 1800
        if: steps.first-attempt.outcome == 'failure'
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          SHOW_TITLE: false
          COMMIT_MESSAGE: ⚡ Updated Weekly Coding Stats
        if: steps.first-attempt.outcome == 'failure'
  timespans:
    name: Update Readme with current timespans
    runs-on: ubuntu-latest
    steps:
      - uses: Taucher2003/date-difference-action@master
        with:
          COMMIT_MESSAGE: ⏰ Updated time differences
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          1: ${{ secrets.BIRTHDAY }}
